"""
src/renderer/objects.py
========================
3D object definitions using VBOs (Vertex Buffer Objects) via PyOpenGL.

WHY VBOs?
---------
Immediate mode (glBegin/glVertex3fv/glEnd) sends vertex data from CPU to GPU
per-frame with a function call per vertex.  This is deprecated in OpenGL 3+ and
has measurable overhead even in older contexts.

VBO approach:
 1. Upload vertex data to GPU memory *once* on construction.
 2. Each frame: bind VAO/VBO, draw.  No per-vertex CPU→GPU copy.
 3. Cleaner abstraction: each object owns its own GPU buffers.

For GLU quadrics (sphere, cylinder) the geometry is generated at runtime by
GLU — we keep those as-is since GLU doesn't expose raw vertices and the objects
are secondary in complexity.

API
---
class HologramObject:
    render() → None

Each concrete class implements render().
"""

import ctypes
import math
from typing import List, Tuple

import numpy as np
from OpenGL.GL import *
from OpenGL.GLU import *


# ---------------------------------------------------------------------------
# Base class
# ---------------------------------------------------------------------------

class HologramObject:
    name: str = "Object"

    def render(self) -> None:
        raise NotImplementedError

    def cleanup(self) -> None:
        """Release GPU resources."""
        pass


# ---------------------------------------------------------------------------
# Generic wireframe VBO object
# ---------------------------------------------------------------------------

class WireframeVBO(HologramObject):
    """
    Generic wireframe object backed by a VBO.

    vertices : list of (x, y, z) tuples
    edges    : list of (i, j) index pairs
    color    : (r, g, b) floats [0, 1]
    """

    def __init__(
        self,
        name: str,
        vertices: List[Tuple[float, float, float]],
        edges: List[Tuple[int, int]],
        color: Tuple[float, float, float],
    ):
        self.name = name
        self._color = color

        # Build a flat vertex array in edge-list order (each edge = 2 vertices)
        raw: List[float] = []
        for (i, j) in edges:
            v0 = vertices[i]
            v1 = vertices[j]
            raw.extend(v0)
            raw.extend(v1)

        self._vertex_count = len(edges) * 2
        arr = np.array(raw, dtype=np.float32)

        # Upload to GPU
        self._vbo = glGenBuffers(1)
        glBindBuffer(GL_ARRAY_BUFFER, self._vbo)
        glBufferData(GL_ARRAY_BUFFER, arr.nbytes, arr, GL_STATIC_DRAW)
        glBindBuffer(GL_ARRAY_BUFFER, 0)

    def render(self) -> None:
        glColor3f(*self._color)
        glEnableClientState(GL_VERTEX_ARRAY)
        glBindBuffer(GL_ARRAY_BUFFER, self._vbo)
        glVertexPointer(3, GL_FLOAT, 0, None)
        glDrawArrays(GL_LINES, 0, self._vertex_count)
        glBindBuffer(GL_ARRAY_BUFFER, 0)
        glDisableClientState(GL_VERTEX_ARRAY)

    def cleanup(self) -> None:
        glDeleteBuffers(1, [self._vbo])


# ---------------------------------------------------------------------------
# GLU-based objects (geometry generated by GLU, non-VBO)
# ---------------------------------------------------------------------------

class _GLUSolid(HologramObject):
    def __init__(self, name: str, color: Tuple[float, float, float]):
        self.name  = name
        self._color = color

    def _make_q(self, style=None):
        q = gluNewQuadric()
        if style is not None:
            gluQuadricDrawStyle(q, style)
        return q


class SolidSphere(_GLUSolid):
    def render(self):
        glColor3f(*self._color)
        gluSphere(self._make_q(), 1, 40, 40)


class WireSphereObj(_GLUSolid):
    def render(self):
        glColor3f(*self._color)
        gluSphere(self._make_q(GLU_LINE), 1, 20, 20)


class CylinderObj(_GLUSolid):
    def render(self):
        glColor3f(*self._color)
        gluCylinder(self._make_q(), 1, 1, 2, 32, 32)


# ---------------------------------------------------------------------------
# Object catalogue
# ---------------------------------------------------------------------------

def build_object_catalogue() -> List[HologramObject]:
    """
    Construct all objects.  Must be called AFTER OpenGL context is ready
    (VBO upload requires an active GL context).
    """
    objects: List[HologramObject] = []

    # ── Cube ────────────────────────────────────────────────────────────────
    _cube_verts = [
        ( 1,-1,-1),( 1, 1,-1),(-1, 1,-1),(-1,-1,-1),
        ( 1,-1, 1),( 1, 1, 1),(-1,-1, 1),(-1, 1, 1),
    ]
    _cube_edges = [
        (0,1),(0,3),(0,4),(2,1),(2,3),(2,7),
        (6,3),(6,4),(6,7),(5,1),(5,4),(5,7),
    ]
    objects.append(WireframeVBO("Cube", _cube_verts, _cube_edges, (0,1,1)))

    # ── Pyramid ─────────────────────────────────────────────────────────────
    _pyr_verts = [(0,1,0),(-1,-1,1),(1,-1,1),(1,-1,-1),(-1,-1,-1)]
    _pyr_edges = [(0,1),(0,2),(0,3),(0,4),(1,2),(2,3),(3,4),(4,1)]
    objects.append(WireframeVBO("Pyramid", _pyr_verts, _pyr_edges, (1,0,1)))

    # ── Sphere ──────────────────────────────────────────────────────────────
    objects.append(SolidSphere("Sphere", (0,1,0)))

    # ── Diamond ─────────────────────────────────────────────────────────────
    _dia_verts = [(0,1,0),(1,0,0),(0,-1,0),(-1,0,0),(0,0,1),(0,0,-1)]
    _dia_edges = [(0,1),(0,3),(0,4),(0,5),(2,1),(2,3),(2,4),(2,5)]
    objects.append(WireframeVBO("Diamond", _dia_verts, _dia_edges, (1,1,0)))

    # ── Cylinder ────────────────────────────────────────────────────────────
    objects.append(CylinderObj("Cylinder", (0,0.5,1)))

    # ── Double Pyramid ───────────────────────────────────────────────────────
    _dp_verts = [(0,1,0),(-1,0,1),(1,0,1),(1,0,-1),(-1,0,-1),(0,-1,0)]
    _dp_edges = [(0,1),(0,2),(0,3),(0,4),(5,1),(5,2),(5,3),(5,4),(1,2),(2,3),(3,4),(4,1)]
    objects.append(WireframeVBO("Double Pyramid", _dp_verts, _dp_edges, (1,0,0)))

    # ── Wire Sphere ─────────────────────────────────────────────────────────
    objects.append(WireSphereObj("Wire Sphere", (1,0.5,0)))

    # ── Wire Cube ───────────────────────────────────────────────────────────
    objects.append(WireframeVBO("Wire Cube", _cube_verts, _cube_edges, (1,1,1)))

    return objects
